name: commons
description: A new Flutter package project.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  json_serializable : ^3.3.0
dev_dependencies:
  build_runner: ^1.10.0
